[package]
name = "mapper"
version = "0.1.0"
authors = ["Vova <vova616@gmail.com>"]
edition = "2018"

[dependencies]
smallvec = "0.6.9"
mapper-derive = { path = "../mapper_derive", optional = true }

[features]
default = ["derive"]
derive = ["mapper-derive"]
